---
- hosts: all
  become: yes
  tasks:
  - include_tasks: file.yml
  - name: install webserver on redhat
    yum:
      name: httpd
      state: present
    notify: startwebserver

  - name: copy index file into webserver
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify: startwebserver
      
  handlers:   
  - name: startwebserver
    service:
      name: httpd
      state: started

  - name: stopwebserver
    service:
      name: httpd
      state: stoped