---
- hosts: all 
  become: yes
  tasks:
   - name: displaying host name
     command: hostname -f
     register: result
   - name: display result value
     debug:
        msg: "{{result}}"

   - name: install git using condition
     yum:
       name: git
       state: present          
     when: result.stderr ==""
     
   - name: install tree using condition
     yum:
        name: tree
        state: present
     when: result.stderr !=""   
   